(defun insert-at (elem lst pos)
  (labels ((insert-at* (lst pos prefix)
			 (if (or (null lst) (= pos 1))
				 (append (reverse prefix) (cons elem lst))
				 (insert-at* (rest lst) (1- pos) (cons (first lst) prefix)))))
	(insert-at* lst pos nil)))
