(defun prime-factors (n)
  (do ((i 2) (res nil))
      ((= n 1) (reverse res))
    (if (= (rem n i) 0)
        (progn (setq res (cons i res))
               (setq n (/ n i)))
        (setq i (1+ i)))))
